"cancer" : "C:/Users/marsh/Desktop/datasets/breast-cancer.csv"
"liver" : "C:/Users/marsh/Desktop/datasets/liver_cancer.csv"
"sensor" : "C:/Users/marsh/Desktop/datasets/sensor.csv"
"price" : "/homes/memartinus/Desktop/Machine_learning/4/price.csv"


