"cancer" : "/homes/memartinus/Desktop/Machine_learning/1/cancer_data.csv"
"liver" : "C:/Users/marsh/Desktop/datasets/liver_cancer.csv"
"sensor" : "/homes/memartinus/Desktop/Machine_learning/3/sensor.csv"
